version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: afrobeatsno/agent-system:dev
    container_name: afrobeats-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./cache:/app/cache
      - ./.env:/app/.env
    environment:
      - PORT=8000
      - ENVIRONMENT=development
      - ENABLE_CACHE=true
    networks:
      - afrobeats-network

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    image: afrobeatsno/frontend:dev
    container_name: afrobeats-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      - NEXT_PUBLIC_API_URL=http://api:8000
    networks:
      - afrobeats-network

networks:
  afrobeats-network:
    name: afrobeats-network